# Generated by Django 5.1.7 on 2025-03-25 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('opponent', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('game_type', models.CharField(help_text="E.g., 'pub league', 'friendly'", max_length=50)),
                ('cycles_per_round', models.PositiveIntegerField(default=3)),
                ('team_first', models.BooleanField(default=True, help_text='Does Keith’s team start first?')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GamePlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_players', to='scores.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scores.player')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField()),
                ('cycle_number', models.PositiveIntegerField()),
                ('roll1', models.PositiveIntegerField(blank=True, null=True)),
                ('roll2', models.PositiveIntegerField(blank=True, null=True)),
                ('roll3', models.PositiveIntegerField(blank=True, null=True)),
                ('total', models.PositiveIntegerField(default=0)),
                ('is_strike', models.BooleanField(default=False)),
                ('is_spare', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='scores.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scores.player')),
            ],
        ),
    ]
