# Generated by Django 5.1.7 on 2025-03-25 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='team_first',
            field=models.BooleanField(db_column='first_team', default=True, help_text='Does Keith’s team start first?'),
        ),
    ]
