# Generated by Django 5.1.7 on 2025-03-25 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0002_alter_game_team_first'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='roll1',
            field=models.PositiveIntegerField(blank=True, db_column='roll_1', null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='roll2',
            field=models.PositiveIntegerField(blank=True, db_column='roll_2', null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='roll3',
            field=models.PositiveIntegerField(blank=True, db_column='roll_3', null=True),
        ),
    ]
