# Generated by Django 5.1.7 on 2025-03-25 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0003_alter_score_roll1_alter_score_roll2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('help_text', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='gameplayer',
            name='team',
            field=models.CharField(choices=[('own', 'Own Team'), ('opp', 'Opposing Team')], default='own', max_length=4),
        ),
        migrations.AlterField(
            model_name='game',
            name='team_first',
            field=models.BooleanField(db_column='first_team', default=True, help_text='Does your team start first?'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_type',
            field=models.ForeignKey(help_text="E.g., 'pub league', 'friendly'", on_delete=django.db.models.deletion.PROTECT, related_name='games', to='scores.gametype'),
        ),
        migrations.AlterField(
            model_name='game',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='games', to='scores.location'),
        ),
    ]
