# Generated by Django 5.1.7 on 2025-03-25 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0004_gametype_location_gameplayer_team_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gametype',
            name='help_text',
        ),
        migrations.AlterField(
            model_name='game',
            name='game_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scores.gametype'),
        ),
        migrations.AlterField(
            model_name='game',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scores.location'),
        ),
        migrations.AlterField(
            model_name='gameplayer',
            name='team',
            field=models.CharField(choices=[('own', 'Own Team'), ('opp', 'Opposing Team')], max_length=4),
        ),
        migrations.AlterField(
            model_name='gametype',
            name='name',
            field=models.CharField(help_text="E.g., 'pub league', 'friendly'", max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
