# Generated by Django 5.1.7 on 2025-03-25 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0005_remove_gametype_help_text_alter_game_game_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_type',
            field=models.ForeignKey(db_column='game_type', null=True, on_delete=django.db.models.deletion.SET_NULL, to='scores.gametype'),
        ),
        migrations.AlterField(
            model_name='game',
            name='location',
            field=models.ForeignKey(db_column='location', null=True, on_delete=django.db.models.deletion.SET_NULL, to='scores.location'),
        ),
    ]
